apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ytfrrjct2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-go:ab265608e2b58cbddd527fafc9d630551332a9e5@sha256:6facef3ba368618d5bb40f4a94e6847c9771dc55301714dd8e01fcc24fa2b1d3
          name: container-image
